spring:
  application:
    name: KanbanApi
  jpa:
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: aurora123
server:
  servlet:
    context-path: /kanban-api
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
app:
  jwt:
    secret: mQgFNWSrwQARkCydK40ts0BOwJarGYAd9f2xnrBKHDzE09w4PWT9qHwtbM23Kola
    expiration: 3600000